import Image from "./images/Image";

const data = [
  {
    id: 5,
    img: Image.spaceShooterJS,
    name: "Space shooter on JS v1.1",
    using: "Canvas",
    language: "JavaScript",
    repoName: "JS-Game_SpaceShooter",
    update: "19.04.2023",
    urlDemo: "https://paveldrobny.github.io/JS-Game_SpaceShooter/",
    urlCode: "https://github.com/paveldrobny/JS-Game_SpaceShooter",
    isShow: true,
    isDemo: true,
    publishData: 1675544213316
  },
  {
    id: 4,
    img: Image.unityQuestSystem,
    name: "Unity Quest System v2.1",
    using: "Unity 2022",
    language: "C#",
    repoName: "Unity_QuestSystem",
    update: "24.12.2022",
    urlCode: "https://github.com/paveldrobny/Unity_QuestSystem",
    isShow: true,
  },
  {
    id: 3,
    img: Image.platformerJS,
    name: "Platformer on JS with EDITOR",
    using: "SVG, Canvas",
    language: "JavaScript",
    repoName: "PlatformerJS",
    update: "01.08.2023",
    urlDemo: "https://paveldrobny.github.io/PlatformerJS/",
    urlCode: "https://github.com/paveldrobny/PlatformerJS",
    isShow: true,
    isDemo: true,
  },
  {
    id: 2,
    img: Image.hudInformation,
    name: "HUD information",
    using: "Unreal Engine 4.26",
    language: "C++, Blueprints",
    repoName: "UE4_HUDInformation",
    update: "04.09.2022",
    urlCode: "https://github.com/paveldrobny/UE4_HUDInformation",
    isShow: true,
  },
  {
    id: 1,
    img: Image.pingPongJS,
    name: "Ping Pong on JS",
    using: "Canvas",
    language: "JavaScript",
    repoName: "JS-Game_PingPong",
    update: "10.03.2022",
    urlDemo: "https://paveldrobny.github.io/JS-Game_PingPong/",
    urlCode: "https://github.com/paveldrobny/JS-Game_PingPong",
    isShow: true,
    isDemo: true,
  },
];

export default data;
